# Generated by Django 4.2.4 on 2023-10-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0025_biddingprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingprocess',
            name='bid_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='biddingprocess',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
