# Generated by Django 4.2.4 on 2023-10-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0026_biddingprocess_bid_price_biddingprocess_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingprocess',
            name='total_buy_pine',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
