# Generated by Django 4.2.4 on 2023-10-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0027_biddingprocess_total_buy_pine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingprocess',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
